ELECTED_SP_STATE_DEP = ['andreawerner_', 'edianemariamtst', 'simaopedro_sp', 'bfeministapsol', 'carteiroreaca', 'majormecca', 'leosiqueirabr', 'valbolsonaro', 'carlosgiannazi', 'danilobalas', 'emidiodesouza_', 'caiofranca40', 'esuplicy', 'edmirchedid', 'marcialiapt13', 'anaperugini', 'thainarafariapt', 'depeniotatto', 'itamar_borges', 'professorabebel', 'prcarloscezar', 'sppretas', 'valdomirolopes_', 'tenente_coimbra', 'bethsahao', 'xerifedoconsum', 'deputadomaurici', 'rafaelsaraivasp', 'contelopes', 'lucasbovesp', 'zimbaldirafa', 'lcmarcolino', 'paulomansur_', 'auricchiothiago', 'dreltonjr', 'vcamarinha', 'marcosdamasiosp', 'fabibbolsonaro', 'danialonsoda', 'brunozambelli3', ]
NON_ELECTED_SP_STATE_DEP = ['77_frota', 'valeriabnews', 'ailtonamaral11', 'ffasanojr', 'dudahidalgo13', 'viniciusaithsp', 'keitlimasp', 'renatafalzoni', 'sidneimedeiros8', 'pauloeneas', 'leolimapsc20', 'adeliaeleicao22', 'deiabatista', 'evertonsodario', 'gtavarespcb', 'vaipaolla', 'edsonsalomaosp', 'neon_cunha', 'victorlinssp', 'lucaspavanato', 'carmensilvamstc', 'mairamrt', 'psol_ricardo', 'anacmielke', 'gersonspires', 'raulmarcelo_', 'bonicoverrei', 'celamericosp', 'eddyantonini', 'profwagnerromao', 'marilacerdareal', 'gplacce', 'inespazpsol', 'chirleypankara', 'isabelarahalsp', 'emersonosasco', 'abidanhenrique', 'uriafancelli', 'eduardo32812197', 'paulobufalopsol', 'jucianecunhaofc', 'ednadellanina1', 'claumontanari', 'rodrigorey', 'fernandopuga13', 'miriam_algarra', 'nhambiquara1', 'aldodemarchi', 'rafael_zucco', 'caiquemafra10', 'soudree', 'campos_machado', 'daniel_neves', 'finafinessi', 'rodrigo_nahas', 'edneyduartejr', 'olindacaetano', 'drmarcioaurelio', 'rafaelmorenoss', 'grisogiuliano', 'peresedu', 'araujobr_', 'ogabelem', 'equimarciliasfr', 'lucaspzanatta', 'doutorli', 'acynthiamichels', 'sergiovictorbr', 'tennascimento', 'lsimabukulo', 'eusoumuniz', 'maemirellebueno', 'miriamantunesbr', 'edilsonmarciano', 'ire_juliani', 'fabiojabadgtal', 'gallinatiraquel', 'romeuescanhoela', 'estelaalmagro13', 'mayaratorressp', 'laerciobenko', 'victormarquessp', 'borgoadriana', 'marceloaguiarof', 'monicacurynovo', 'gbarbieratto', 'alex_minduin', 'vitorkundrat', 'rronaldosantoss', 'alexyasalvador', 'carmona_sp', 'audrey_kleys', 'marcelodelbosco', 'wilsonmellosp', 'fragavereadora', 'gilmarlucas_', 'demartiniuc', 'rafaelpintersp', 'marcelo65079046', 'marinadamantiq1', 'thiago_pt13', 'marcelo_nasci', 'amanzanosp', 'dante_mantovani', 'matheuslemes_sp', 'danilopalmasp', 'tiago_1914', 'alemustafa', 'graziela_dra', 'renato_moreni', 'marcionovo30', 'evandrovaronil', 'edsonjapaobr', 'dgmartinsdm', 'fernand05071922', 'valdomiro_forum', 'sergiosantanapl', 'wilsonkmatos', 'mahomsi', 'taticriscuolo', 'barbezani', 'wesleypeixotoo', 'souricardofaria', 'anapetili', 'janetepieta', 'andrebuenoofc', 'arraes_dilmapt', 'andreanerisant1', 'enidcarvalho2', 'deralusgarry', 'cadunovosp', 'zoraidalobato', 'emmersoncamargo', 'petersonruansp', 'fabiosantos_sp', 'jsalvetti', 'edsonpc_7', 'prasandragio', 'sargentogato1', 'andreluisbraga', 'eurafabernardo', 'felipedavila', 'pericles_regis', 'profchrisgrace', 'saulo_souza', 'protetorale', 'damarismouradra', 'jrteixeira40', 'honnocahon', 'marcosfurlanbr', 'vileladarodagem', 'evelynd74966131', 'sdmadalhano', 'lucasdoliceu', 'jandyraueharapt', 'albino_vereador', 'valmarac', 'juliocesarevoce', 'crisoliveiracps', ]

SCRAPPING_PERIODS = [
    {'since': '2022-09-01', 'until': '2022-10-01'},
    {'since': '2022-10-01', 'until': '2022-11-01'},
    {'since': '2022-11-01', 'until': '2022-12-01'},
    {'since': '2022-12-01', 'until': '2023-01-01'},
    {'since': '2023-01-01', 'until': '2023-02-01'},
    {'since': '2023-02-01', 'until': '2023-03-01'},
    {'since': '2023-03-01', 'until': '2023-04-01'},
]