version: '3'

services:
  web:
    build: ./twitter_scrapping
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./twitter_scrapping/:/usr/src/twitter_scrapping/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
  celery:
    image: celery:latest
    container_name: celery
    command: celery -A twitter_scrapping worker -l INFO -f celery.log

  flower:  
    image: mher/flower
    container_name: flower
    command: celery flower
