import datetime
from copy import deepcopy
from django.utils import timezone
from snscrape.modules.twitter import (
    User as SNUser,
    Tweet as SNTweet,
    Tombstone,
    TweetRef,
    TextLink,
    SummaryCard,
    Photo,
)


normal_tweet = SNTweet(
    url="https://twitter.com/GergelyOrosz/status/1651646573225418756",
    date=datetime.datetime(2023, 4, 27, 17, 56, 43, tzinfo=datetime.timezone.utc),
    rawContent='Maybe this is strange, but earlier in my career, I was always "afraid" of my managers at first. When they called a meeting with me, I thought I could be in trouble for something. I never expected much good from my "boss."\n\nWhen I became a manager, I realized how this was all odd:',
    renderedContent='Maybe this is strange, but earlier in my career, I was always "afraid" of my managers at first. When they called a meeting with me, I thought I could be in trouble for something. I never expected much good from my "boss."\n\nWhen I became a manager, I realized how this was all odd:',
    id=1651646573225418756,
    user=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: https://t.co/MJ0eAtlaS1. Contact: https://t.co/POWftUprCb",
        renderedDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: pragmaticurl.com/talent. Contact: pragmaticurl.com/contact",
        descriptionLinks=[
            TextLink(
                text="pragmaticurl.com/talent",
                url="http://pragmaticurl.com/talent",
                tcourl="https://t.co/MJ0eAtlaS1",
                indices=(102, 125),
            ),
            TextLink(
                text="pragmaticurl.com/contact",
                url="http://pragmaticurl.com/contact",
                tcourl="https://t.co/POWftUprCb",
                indices=(136, 159),
            ),
        ],
        verified=False,
        created=datetime.datetime(2009, 4, 10, 10, 1, 11, tzinfo=datetime.timezone.utc),
        followersCount=209095,
        friendsCount=1395,
        statusesCount=25953,
        favouritesCount=33241,
        listedCount=2344,
        mediaCount=2617,
        location="Amsterdam, The Netherlands",
        protected=False,
        link=TextLink(
            text="pragmaticengineer.com",
            url="https://pragmaticengineer.com/",
            tcourl="https://t.co/x8RulFU4ID",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/673095429748350976/ei5eeouV_normal.png",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/30192824/1619604364",
        label=None,
    ),
    replyCount=16,
    retweetCount=29,
    likeCount=519,
    quoteCount=5,
    conversationId=1651646573225418756,
    lang="en",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=None,
    retweetedTweet=None,
    quotedTweet=None,
    inReplyToTweetId=None,
    inReplyToUser=None,
    mentionedUsers=None,
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=82748,
    vibe=None,
)


tweet_with_quoted_tweet = SNTweet(
    url="https://twitter.com/GergelyOrosz/status/1636295637187584000",
    date=datetime.datetime(2023, 3, 16, 9, 17, 35, tzinfo=datetime.timezone.utc),
    rawContent="When I talked w ~70 companies about what vendor costs they are reducing, the two most frequently mentioned was AWS/GCP and Datadog. Simply because they were usually by far the biggest spend.\n\nGiven DDG is usage based, reducing it is usually easier.\n\nMore:  https://t.co/NxOVEcYCds",
    renderedContent="When I talked w ~70 companies about what vendor costs they are reducing, the two most frequently mentioned was AWS/GCP and Datadog. Simply because they were usually by far the biggest spend.\n\nGiven DDG is usage based, reducing it is usually easier.\n\nMore:  newsletter.pragmaticengineer.com/p/vendor-spend…",
    id=1636295637187584000,
    user=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: https://t.co/MJ0eAtlaS1. Contact: https://t.co/POWftUprCb",
        renderedDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: pragmaticurl.com/talent. Contact: pragmaticurl.com/contact",
        descriptionLinks=[
            TextLink(
                text="pragmaticurl.com/talent",
                url="http://pragmaticurl.com/talent",
                tcourl="https://t.co/MJ0eAtlaS1",
                indices=(102, 125),
            ),
            TextLink(
                text="pragmaticurl.com/contact",
                url="http://pragmaticurl.com/contact",
                tcourl="https://t.co/POWftUprCb",
                indices=(136, 159),
            ),
        ],
        verified=False,
        created=datetime.datetime(2009, 4, 10, 10, 1, 11, tzinfo=datetime.timezone.utc),
        followersCount=209092,
        friendsCount=1395,
        statusesCount=25953,
        favouritesCount=33241,
        listedCount=2344,
        mediaCount=2617,
        location="Amsterdam, The Netherlands",
        protected=False,
        link=TextLink(
            text="pragmaticengineer.com",
            url="https://pragmaticengineer.com/",
            tcourl="https://t.co/x8RulFU4ID",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/673095429748350976/ei5eeouV_normal.png",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/30192824/1619604364",
        label=None,
    ),
    replyCount=22,
    retweetCount=14,
    likeCount=236,
    quoteCount=3,
    conversationId=1636295637187584000,
    lang="en",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=[
        TextLink(
            text="newsletter.pragmaticengineer.com/p/vendor-spend…",
            url="https://newsletter.pragmaticengineer.com/p/vendor-spend-cuts",
            tcourl="https://t.co/NxOVEcYCds",
            indices=(257, 280),
        )
    ],
    media=None,
    retweetedTweet=None,
    quotedTweet=SNTweet(
        url="https://twitter.com/jamesacowling/status/1636168208377077760",
        date=datetime.datetime(2023, 3, 16, 0, 51, 14, tzinfo=datetime.timezone.utc),
        rawContent="Real monthly bills at an early-stage startup:\n\n@datadoghq: $11,386\n@getsentry: $134",
        renderedContent="Real monthly bills at an early-stage startup:\n\n@datadoghq: $11,386\n@getsentry: $134",
        id=1636168208377077760,
        user=SNUser(
            username="jamesacowling",
            id=738506197158895616,
            displayname="James Cowling",
            rawDescription="@convex_dev co-founder. Infrastructure person. Reformed academic. Maker of things. Karaoke enthusiast.",
            renderedDescription="@convex_dev co-founder. Infrastructure person. Reformed academic. Maker of things. Karaoke enthusiast.",
            descriptionLinks=None,
            verified=False,
            created=datetime.datetime(
                2016, 6, 2, 23, 2, 53, tzinfo=datetime.timezone.utc
            ),
            followersCount=837,
            friendsCount=169,
            statusesCount=193,
            favouritesCount=284,
            listedCount=20,
            mediaCount=8,
            location="San Francisco, CA",
            protected=False,
            link=TextLink(
                text="convex.dev",
                url="http://convex.dev",
                tcourl="https://t.co/HAhmzsryzZ",
                indices=(0, 23),
            ),
            profileImageUrl="https://pbs.twimg.com/profile_images/1550543886610640896/3JztoI2B_normal.jpg",
            profileBannerUrl="https://pbs.twimg.com/profile_banners/738506197158895616/1661050219",
            label=None,
        ),
        replyCount=59,
        retweetCount=41,
        likeCount=701,
        quoteCount=22,
        conversationId=1636168208377077760,
        lang="en",
        source=None,
        sourceUrl=None,
        sourceLabel=None,
        links=None,
        media=None,
        retweetedTweet=None,
        quotedTweet=None,
        inReplyToTweetId=None,
        inReplyToUser=None,
        mentionedUsers=[
            SNUser(
                username="datadoghq",
                id=123093566,
                displayname="Datadog, Inc.",
                rawDescription=None,
                renderedDescription=None,
                descriptionLinks=None,
                verified=None,
                created=None,
                followersCount=None,
                friendsCount=None,
                statusesCount=None,
                favouritesCount=None,
                listedCount=None,
                mediaCount=None,
                location=None,
                protected=None,
                link=None,
                profileImageUrl=None,
                profileBannerUrl=None,
                label=None,
            ),
            SNUser(
                username="getsentry",
                id=464217126,
                displayname="Sentry",
                rawDescription=None,
                renderedDescription=None,
                descriptionLinks=None,
                verified=None,
                created=None,
                followersCount=None,
                friendsCount=None,
                statusesCount=None,
                favouritesCount=None,
                listedCount=None,
                mediaCount=None,
                location=None,
                protected=None,
                link=None,
                profileImageUrl=None,
                profileBannerUrl=None,
                label=None,
            ),
        ],
        coordinates=None,
        place=None,
        hashtags=None,
        cashtags=None,
        card=None,
        viewCount=451120,
        vibe=None,
    ),
    inReplyToTweetId=None,
    inReplyToUser=None,
    mentionedUsers=None,
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=SummaryCard(
        title="Are Tech Companies Aggressively Cutting Back on Vendor Spend?",
        url="https://newsletter.pragmaticengineer.com/p/vendor-spend-cuts",
        description="A deep dive into why vendor cuts are happening, which areas are most impacted, and actionable advice on how to save costs. With data points from more than 70 companies.",
        thumbnailUrl="https://pbs.twimg.com/card_img/1650940225214881794/wip5cEzU?format=jpg&name=orig",
        siteUser=None,
        creatorUser=None,
    ),
    viewCount=163706,
    vibe=None,
)


tweet_with_quoted_tombstone = SNTweet(
    url="https://twitter.com/joicehasselmann/status/1570465162586640391",
    date=datetime.datetime(2022, 9, 15, 17, 30, 47, tzinfo=datetime.timezone.utc),
    rawContent="Torcendo pela retomada do @o_antagonista e @RevistaCrusoe .",
    renderedContent="Torcendo pela retomada do @o_antagonista e @RevistaCrusoe .",
    id=1570465162586640391,
    user=SNUser(
        username="joicehasselmann",
        id=116519514,
        displayname="Joice Hasselmann",
        rawDescription="",
        renderedDescription="",
        descriptionLinks=None,
        verified=False,
        created=datetime.datetime(
            2010, 2, 22, 19, 13, 22, tzinfo=datetime.timezone.utc
        ),
        followersCount=409153,
        friendsCount=247,
        statusesCount=62166,
        favouritesCount=13775,
        listedCount=1533,
        mediaCount=6028,
        location="Sao Paulo, Brazil",
        protected=False,
        link=TextLink(
            text="youtube.com/joicehasselmann",
            url="http://www.youtube.com/joicehasselmann",
            tcourl="https://t.co/5q59CwkohA",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/1620576880838443013/M2JneeOF_normal.jpg",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/116519514/1675210623",
        label=None,
    ),
    replyCount=12,
    retweetCount=3,
    likeCount=32,
    quoteCount=1,
    conversationId=1570465162586640391,
    lang="pt",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=None,
    retweetedTweet=None,
    quotedTweet=Tombstone(
        id=1570433495239135232,
        text="This Tweet is from an account that no longer exists. Learn more",
        textLinks=[
            TextLink(
                text="Learn more",
                url="https://help.twitter.com/rules-and-policies/notices-on-twitter",
                tcourl=None,
                indices=(53, 63),
            )
        ],
    ),
    inReplyToTweetId=None,
    inReplyToUser=None,
    mentionedUsers=[
        SNUser(
            username="o_antagonista",
            id=2880932962,
            displayname="O Antagonista",
            rawDescription=None,
            renderedDescription=None,
            descriptionLinks=None,
            verified=None,
            created=None,
            followersCount=None,
            friendsCount=None,
            statusesCount=None,
            favouritesCount=None,
            listedCount=None,
            mediaCount=None,
            location=None,
            protected=None,
            link=None,
            profileImageUrl=None,
            profileBannerUrl=None,
            label=None,
        ),
        SNUser(
            username="RevistaCrusoe",
            id=967904717446766593,
            displayname="Revista Crusoé",
            rawDescription=None,
            renderedDescription=None,
            descriptionLinks=None,
            verified=None,
            created=None,
            followersCount=None,
            friendsCount=None,
            statusesCount=None,
            favouritesCount=None,
            listedCount=None,
            mediaCount=None,
            location=None,
            protected=None,
            link=None,
            profileImageUrl=None,
            profileBannerUrl=None,
            label=None,
        ),
    ],
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=None,
    vibe=None,
)

tweet_with_retweet = SNTweet(
    url="https://twitter.com/erosbiondini/status/1615401658292355072",
    date=datetime.datetime(2023, 1, 17, 17, 32, 22, tzinfo=datetime.timezone.utc),
    rawContent="RT @em_com: VOCÊ VIU?\nMinistra da Saúde revoga norma que dificultava aborto legal. O texto destacava a necessidade de comunicar o fato à au…",
    renderedContent="RT @em_com: VOCÊ VIU?\nMinistra da Saúde revoga norma que dificultava aborto legal. O texto destacava a necessidade de comunicar o fato à au…",
    id=1615401658292355072,
    user=SNUser(
        username="erosbiondini",
        id=59449883,
        displayname="Eros Biondini",
        rawDescription="Cantor/Missionário/Veterinário/Deputado Federal #musicacatolica #musicacrista",
        renderedDescription="Cantor/Missionário/Veterinário/Deputado Federal #musicacatolica #musicacrista",
        descriptionLinks=None,
        verified=False,
        created=datetime.datetime(
            2009, 7, 23, 12, 47, 58, tzinfo=datetime.timezone.utc
        ),
        followersCount=79838,
        friendsCount=1085,
        statusesCount=21795,
        favouritesCount=9739,
        listedCount=620,
        mediaCount=499,
        location="",
        protected=False,
        link=TextLink(
            text="linktr.ee/erosbiondini",
            url="https://linktr.ee/erosbiondini",
            tcourl="https://t.co/CQfMsMupCy",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/1128795095363465216/q4xHwimX_normal.jpg",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/59449883/1587580603",
        label=None,
    ),
    replyCount=0,
    retweetCount=11,
    likeCount=0,
    quoteCount=0,
    conversationId=1615401658292355072,
    lang="pt",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=None,
    retweetedTweet=SNTweet(
        url="https://twitter.com/em_com/status/1615321157586092034",
        date=datetime.datetime(2023, 1, 17, 12, 12, 29, tzinfo=datetime.timezone.utc),
        rawContent="VOCÊ VIU?\nMinistra da Saúde revoga norma que dificultava aborto legal. O texto destacava a necessidade de comunicar o fato à autoridade policial responsável e de se preservar possíveis evidências materiais do crime de estupro\nhttps://t.co/NijRuYxiBL https://t.co/5BsHfESUBH",
        renderedContent="VOCÊ VIU?\nMinistra da Saúde revoga norma que dificultava aborto legal. O texto destacava a necessidade de comunicar o fato à autoridade policial responsável e de se preservar possíveis evidências materiais do crime de estupro\nem.com.br/app/noticia/po… https://t.co/5BsHfESUBH",
        id=1615321157586092034,
        user=SNUser(
            username="em_com",
            id=183398510,
            displayname="Estado de Minas",
            rawDescription="Perfil oficial do Jornal Estado de Minas. \nInstagram: https://t.co/GrYaINL6ms\nFacebook: https://t.co/lX2PIukTw5",
            renderedDescription="Perfil oficial do Jornal Estado de Minas. \nInstagram: instagram.com/estadodeminas/\nFacebook: facebook.com/EstadodeMinas",
            descriptionLinks=[
                TextLink(
                    text="instagram.com/estadodeminas/",
                    url="http://instagram.com/estadodeminas/",
                    tcourl="https://t.co/GrYaINL6ms",
                    indices=(54, 77),
                ),
                TextLink(
                    text="facebook.com/EstadodeMinas",
                    url="http://facebook.com/EstadodeMinas",
                    tcourl="https://t.co/lX2PIukTw5",
                    indices=(88, 111),
                ),
            ],
            verified=False,
            created=datetime.datetime(
                2010, 8, 26, 22, 27, 38, tzinfo=datetime.timezone.utc
            ),
            followersCount=581472,
            friendsCount=398,
            statusesCount=334120,
            favouritesCount=722,
            listedCount=1076,
            mediaCount=113343,
            location="Belo Horizonte",
            protected=False,
            link=TextLink(
                text="em.com.br",
                url="http://www.em.com.br",
                tcourl="https://t.co/uiNISR0ZsJ",
                indices=(0, 23),
            ),
            profileImageUrl="https://pbs.twimg.com/profile_images/1409816346737664000/dIZle52U_normal.jpg",
            profileBannerUrl="https://pbs.twimg.com/profile_banners/183398510/1468846263",
            label=None,
        ),
        replyCount=24,
        retweetCount=11,
        likeCount=62,
        quoteCount=2,
        conversationId=1615321157586092034,
        lang="pt",
        source=None,
        sourceUrl=None,
        sourceLabel=None,
        links=[
            TextLink(
                text="em.com.br/app/noticia/po…",
                url="https://www.em.com.br/app/noticia/politica/2023/01/16/interna_politica,1445546/ministra-da-saude-revoga-norma-que-dificultava-aborto-legal.shtml",
                tcourl="https://t.co/NijRuYxiBL",
                indices=(226, 249),
            )
        ],
        media=[
            Photo(
                previewUrl="https://pbs.twimg.com/media/FmrGAbsXkAAoALj?format=jpg&name=small",
                fullUrl="https://pbs.twimg.com/media/FmrGAbsXkAAoALj?format=jpg&name=orig",
                altText=None,
            )
        ],
        retweetedTweet=None,
        quotedTweet=None,
        inReplyToTweetId=None,
        inReplyToUser=None,
        mentionedUsers=None,
        coordinates=None,
        place=None,
        hashtags=None,
        cashtags=None,
        card=None,
        viewCount=4232,
        vibe=None,
    ),
    quotedTweet=None,
    inReplyToTweetId=None,
    inReplyToUser=None,
    mentionedUsers=[
        SNUser(
            username="em_com",
            id=183398510,
            displayname="Estado de Minas",
            rawDescription=None,
            renderedDescription=None,
            descriptionLinks=None,
            verified=None,
            created=None,
            followersCount=None,
            friendsCount=None,
            statusesCount=None,
            favouritesCount=None,
            listedCount=None,
            mediaCount=None,
            location=None,
            protected=None,
            link=None,
            profileImageUrl=None,
            profileBannerUrl=None,
            label=None,
        )
    ],
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=None,
    vibe=None,
)


tweet_in_reply_to = SNTweet(
    url="https://twitter.com/thiagoghisi/status/1651685072305520640",
    date=datetime.datetime(2023, 4, 27, 20, 29, 42, tzinfo=datetime.timezone.utc),
    rawContent="@GergelyOrosz Same here. \n\nI think most of us in Tech for 15+ years had at least one traumatizing experience with an early manager (from the a previous generation of managers) that created that state of mine of constant fear from anything coming from the higher ups.\n\nI once got a feedback from…",
    renderedContent="@GergelyOrosz Same here. \n\nI think most of us in Tech for 15+ years had at least one traumatizing experience with an early manager (from the a previous generation of managers) that created that state of mine of constant fear from anything coming from the higher ups.\n\nI once got a feedback from…",
    id=1651685072305520640,
    user=SNUser(
        username="thiagoghisi",
        id=49197917,
        displayname="Thiago Ghisi",
        rawDescription="🤹\u200d♂️Director of Engineering at @Nubank. 🇧🇷in🗽. Ex-@Apple. Ex-TW. 🎙Co-Host @EngAdvicePod. 🧗Helping Eng. Leaders to Level Up & Crack Big Tech Interviews.",
        renderedDescription="🤹\u200d♂️Director of Engineering at @Nubank. 🇧🇷in🗽. Ex-@Apple. Ex-TW. 🎙Co-Host @EngAdvicePod. 🧗Helping Eng. Leaders to Level Up & Crack Big Tech Interviews.",
        descriptionLinks=None,
        verified=False,
        created=datetime.datetime(2009, 6, 21, 2, 17, 3, tzinfo=datetime.timezone.utc),
        followersCount=18504,
        friendsCount=2002,
        statusesCount=19784,
        favouritesCount=34966,
        listedCount=459,
        mediaCount=2461,
        location="New York, NY. More 👉",
        protected=False,
        link=TextLink(
            text="typefully.com/thiagoghisi",
            url="https://typefully.com/thiagoghisi",
            tcourl="https://t.co/GkmlaUAppZ",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/1318348892853932033/FxMKmypV_normal.jpg",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/49197917/1653100817",
        label=None,
    ),
    replyCount=1,
    retweetCount=0,
    likeCount=13,
    quoteCount=0,
    conversationId=1651646573225418756,
    lang="en",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=None,
    retweetedTweet=None,
    quotedTweet=None,
    inReplyToTweetId=1651646573225418756,
    inReplyToUser=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription=None,
        renderedDescription=None,
        descriptionLinks=None,
        verified=None,
        created=None,
        followersCount=None,
        friendsCount=None,
        statusesCount=None,
        favouritesCount=None,
        listedCount=None,
        mediaCount=None,
        location=None,
        protected=None,
        link=None,
        profileImageUrl=None,
        profileBannerUrl=None,
        label=None,
    ),
    mentionedUsers=[
        SNUser(
            username="GergelyOrosz",
            id=30192824,
            displayname="Gergely Orosz",
            rawDescription=None,
            renderedDescription=None,
            descriptionLinks=None,
            verified=None,
            created=None,
            followersCount=None,
            friendsCount=None,
            statusesCount=None,
            favouritesCount=None,
            listedCount=None,
            mediaCount=None,
            location=None,
            protected=None,
            link=None,
            profileImageUrl=None,
            profileBannerUrl=None,
            label=None,
        )
    ],
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=2711,
    vibe=None,
)


tweet_replying_another_reply = SNTweet(
    url="https://twitter.com/NikoJedynak/status/1651687162461450393",
    date=datetime.datetime(2023, 4, 27, 20, 38, 1, tzinfo=datetime.timezone.utc),
    rawContent="@thiagoghisi @GergelyOrosz Exactly this",
    renderedContent="@thiagoghisi @GergelyOrosz Exactly this",
    id=1651687162461450393,
    user=SNUser(
        username="NikoJedynak",
        id=711263564728819712,
        displayname="Niko",
        rawDescription="Fascinated/terrified with modern world. Cloud Engineer ☁️",
        renderedDescription="Fascinated/terrified with modern world. Cloud Engineer ☁️",
        descriptionLinks=None,
        verified=False,
        created=datetime.datetime(
            2016, 3, 19, 18, 50, 23, tzinfo=datetime.timezone.utc
        ),
        followersCount=104,
        friendsCount=756,
        statusesCount=1420,
        favouritesCount=21361,
        listedCount=2,
        mediaCount=118,
        location="",
        protected=False,
        link=None,
        profileImageUrl="https://pbs.twimg.com/profile_images/1355892822977761289/t0i8mji1_normal.jpg",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/711263564728819712/1648858249",
        label=None,
    ),
    replyCount=0,
    retweetCount=0,
    likeCount=1,
    quoteCount=0,
    conversationId=1651646573225418756,
    lang="en",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=None,
    retweetedTweet=None,
    quotedTweet=None,
    inReplyToTweetId=1651685072305520640,
    inReplyToUser=SNUser(
        username="thiagoghisi",
        id=49197917,
        displayname="Thiago Ghisi",
        rawDescription=None,
        renderedDescription=None,
        descriptionLinks=None,
        verified=None,
        created=None,
        followersCount=None,
        friendsCount=None,
        statusesCount=None,
        favouritesCount=None,
        listedCount=None,
        mediaCount=None,
        location=None,
        protected=None,
        link=None,
        profileImageUrl=None,
        profileBannerUrl=None,
        label=None,
    ),
    mentionedUsers=[
        SNUser(
            username="thiagoghisi",
            id=49197917,
            displayname="Thiago Ghisi",
            rawDescription=None,
            renderedDescription=None,
            descriptionLinks=None,
            verified=None,
            created=None,
            followersCount=None,
            friendsCount=None,
            statusesCount=None,
            favouritesCount=None,
            listedCount=None,
            mediaCount=None,
            location=None,
            protected=None,
            link=None,
            profileImageUrl=None,
            profileBannerUrl=None,
            label=None,
        ),
        SNUser(
            username="GergelyOrosz",
            id=30192824,
            displayname="Gergely Orosz",
            rawDescription=None,
            renderedDescription=None,
            descriptionLinks=None,
            verified=None,
            created=None,
            followersCount=None,
            friendsCount=None,
            statusesCount=None,
            favouritesCount=None,
            listedCount=None,
            mediaCount=None,
            location=None,
            protected=None,
            link=None,
            profileImageUrl=None,
            profileBannerUrl=None,
            label=None,
        ),
    ],
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=249,
    vibe=None,
)


user_tweet_1 = SNTweet(
    url="https://twitter.com/GergelyOrosz/status/1616756444501807104",
    date=datetime.datetime(2023, 1, 21, 11, 15, 48, tzinfo=datetime.timezone.utc),
    rawContent="Substack launched analytics insights and: wow.\n\nThank you to everyone reading @Pragmatic_Eng! https://t.co/X6owJ8af3N",
    renderedContent="Substack launched analytics insights and: wow.\n\nThank you to everyone reading @Pragmatic_Eng! https://t.co/X6owJ8af3N",
    id=1616756444501807104,
    user=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: https://t.co/MJ0eAtlaS1. Contact: https://t.co/POWftUprCb",
        renderedDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: pragmaticurl.com/talent. Contact: pragmaticurl.com/contact",
        descriptionLinks=[
            TextLink(
                text="pragmaticurl.com/talent",
                url="http://pragmaticurl.com/talent",
                tcourl="https://t.co/MJ0eAtlaS1",
                indices=(102, 125),
            ),
            TextLink(
                text="pragmaticurl.com/contact",
                url="http://pragmaticurl.com/contact",
                tcourl="https://t.co/POWftUprCb",
                indices=(136, 159),
            ),
        ],
        verified=False,
        created=datetime.datetime(2009, 4, 10, 10, 1, 11, tzinfo=datetime.timezone.utc),
        followersCount=209133,
        friendsCount=1395,
        statusesCount=25953,
        favouritesCount=33240,
        listedCount=2344,
        mediaCount=2617,
        location="Amsterdam, The Netherlands",
        protected=False,
        link=TextLink(
            text="pragmaticengineer.com",
            url="https://pragmaticengineer.com/",
            tcourl="https://t.co/x8RulFU4ID",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/673095429748350976/ei5eeouV_normal.png",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/30192824/1619604364",
        label=None,
    ),
    replyCount=43,
    retweetCount=17,
    likeCount=962,
    quoteCount=2,
    conversationId=1616756444501807104,
    lang="en",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=[
        Photo(
            previewUrl="https://pbs.twimg.com/media/Fm_fag0WAAAfQ5U?format=jpg&name=small",
            fullUrl="https://pbs.twimg.com/media/Fm_fag0WAAAfQ5U?format=jpg&name=orig",
            altText="Screenshot saying;\n\nLocation\nThe Pragmatic Engineer is read across 50 US states and 212 countries.\nCOUNTRY\nSUBSCRIBERS\nUnited States\n31%\nIndia\n17%\nUnited Kingdom\n6%\nCanada\n4%\nGermany\n3%\nNEWSLETTER.PRAGMATICENGINEER.COM",
        )
    ],
    retweetedTweet=None,
    quotedTweet=None,
    inReplyToTweetId=None,
    inReplyToUser=None,
    mentionedUsers=[
        SNUser(
            username="Pragmatic_Eng",
            id=1544357434650775552,
            displayname="The Pragmatic Engineer",
            rawDescription=None,
            renderedDescription=None,
            descriptionLinks=None,
            verified=None,
            created=None,
            followersCount=None,
            friendsCount=None,
            statusesCount=None,
            favouritesCount=None,
            listedCount=None,
            mediaCount=None,
            location=None,
            protected=None,
            link=None,
            profileImageUrl=None,
            profileBannerUrl=None,
            label=None,
        )
    ],
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=372216,
    vibe=None,
)
user_tweet_2 = SNTweet(
    url="https://twitter.com/GergelyOrosz/status/1651648398754234368",
    date=datetime.datetime(2023, 4, 27, 18, 3, 59, tzinfo=datetime.timezone.utc),
    rawContent="And yes: managers have authority over their direct reports. This is evidently clear when it comes to performance reviews, promotions (e.g. deciding to nominate or not), or how they can initiate eg PIPs.\n\nThis is a reason it's unlikely your manager can be your friend: at least…",
    renderedContent="And yes: managers have authority over their direct reports. This is evidently clear when it comes to performance reviews, promotions (e.g. deciding to nominate or not), or how they can initiate eg PIPs.\n\nThis is a reason it's unlikely your manager can be your friend: at least…",
    id=1651648398754234368,
    user=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: https://t.co/MJ0eAtlaS1. Contact: https://t.co/POWftUprCb",
        renderedDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: pragmaticurl.com/talent. Contact: pragmaticurl.com/contact",
        descriptionLinks=[
            TextLink(
                text="pragmaticurl.com/talent",
                url="http://pragmaticurl.com/talent",
                tcourl="https://t.co/MJ0eAtlaS1",
                indices=(102, 125),
            ),
            TextLink(
                text="pragmaticurl.com/contact",
                url="http://pragmaticurl.com/contact",
                tcourl="https://t.co/POWftUprCb",
                indices=(136, 159),
            ),
        ],
        verified=False,
        created=datetime.datetime(2009, 4, 10, 10, 1, 11, tzinfo=datetime.timezone.utc),
        followersCount=209133,
        friendsCount=1395,
        statusesCount=25953,
        favouritesCount=33240,
        listedCount=2344,
        mediaCount=2617,
        location="Amsterdam, The Netherlands",
        protected=False,
        link=TextLink(
            text="pragmaticengineer.com",
            url="https://pragmaticengineer.com/",
            tcourl="https://t.co/x8RulFU4ID",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/673095429748350976/ei5eeouV_normal.png",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/30192824/1619604364",
        label=None,
    ),
    replyCount=1,
    retweetCount=0,
    likeCount=100,
    quoteCount=0,
    conversationId=1651646573225418756,
    lang="en",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=None,
    retweetedTweet=None,
    quotedTweet=None,
    inReplyToTweetId=1651647372378664960,
    inReplyToUser=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: https://t.co/MJ0eAtlaS1. Contact: https://t.co/POWftUprCb",
        renderedDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: pragmaticurl.com/talent. Contact: pragmaticurl.com/contact",
        descriptionLinks=[
            TextLink(
                text="pragmaticurl.com/talent",
                url="http://pragmaticurl.com/talent",
                tcourl="https://t.co/MJ0eAtlaS1",
                indices=(102, 125),
            ),
            TextLink(
                text="pragmaticurl.com/contact",
                url="http://pragmaticurl.com/contact",
                tcourl="https://t.co/POWftUprCb",
                indices=(136, 159),
            ),
        ],
        verified=False,
        created=datetime.datetime(2009, 4, 10, 10, 1, 11, tzinfo=datetime.timezone.utc),
        followersCount=209133,
        friendsCount=1395,
        statusesCount=25953,
        favouritesCount=33240,
        listedCount=2344,
        mediaCount=2617,
        location="Amsterdam, The Netherlands",
        protected=False,
        link=TextLink(
            text="pragmaticengineer.com",
            url="https://pragmaticengineer.com/",
            tcourl="https://t.co/x8RulFU4ID",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/673095429748350976/ei5eeouV_normal.png",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/30192824/1619604364",
        label=None,
    ),
    mentionedUsers=None,
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=31605,
    vibe=None,
)
user_tweet_3 = SNTweet(
    url="https://twitter.com/GergelyOrosz/status/1651647372378664960",
    date=datetime.datetime(2023, 4, 27, 17, 59, 54, tzinfo=datetime.timezone.utc),
    rawContent="Another thing is how, at least in tech, most managers don't get much support or training when they become good managers. Many did not even have good managers!\n\nSo plenty of managers miss even the basics on what *their* role is, and what success looks for a manager (and how it's…",
    renderedContent="Another thing is how, at least in tech, most managers don't get much support or training when they become good managers. Many did not even have good managers!\n\nSo plenty of managers miss even the basics on what *their* role is, and what success looks for a manager (and how it's…",
    id=1651647372378664960,
    user=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: https://t.co/MJ0eAtlaS1. Contact: https://t.co/POWftUprCb",
        renderedDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: pragmaticurl.com/talent. Contact: pragmaticurl.com/contact",
        descriptionLinks=[
            TextLink(
                text="pragmaticurl.com/talent",
                url="http://pragmaticurl.com/talent",
                tcourl="https://t.co/MJ0eAtlaS1",
                indices=(102, 125),
            ),
            TextLink(
                text="pragmaticurl.com/contact",
                url="http://pragmaticurl.com/contact",
                tcourl="https://t.co/POWftUprCb",
                indices=(136, 159),
            ),
        ],
        verified=False,
        created=datetime.datetime(2009, 4, 10, 10, 1, 11, tzinfo=datetime.timezone.utc),
        followersCount=209133,
        friendsCount=1395,
        statusesCount=25953,
        favouritesCount=33240,
        listedCount=2344,
        mediaCount=2617,
        location="Amsterdam, The Netherlands",
        protected=False,
        link=TextLink(
            text="pragmaticengineer.com",
            url="https://pragmaticengineer.com/",
            tcourl="https://t.co/x8RulFU4ID",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/673095429748350976/ei5eeouV_normal.png",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/30192824/1619604364",
        label=None,
    ),
    replyCount=10,
    retweetCount=2,
    likeCount=191,
    quoteCount=1,
    conversationId=1651646573225418756,
    lang="en",
    source=None,
    sourceUrl=None,
    sourceLabel=None,
    links=None,
    media=None,
    retweetedTweet=None,
    quotedTweet=None,
    inReplyToTweetId=1651646954898595851,
    inReplyToUser=SNUser(
        username="GergelyOrosz",
        id=30192824,
        displayname="Gergely Orosz",
        rawDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: https://t.co/MJ0eAtlaS1. Contact: https://t.co/POWftUprCb",
        renderedDescription="Writing @Pragmatic_Eng & @EngGuidebook. Advisor @mobile__dev. Formerly Uber & Skype. Great tech jobs: pragmaticurl.com/talent. Contact: pragmaticurl.com/contact",
        descriptionLinks=[
            TextLink(
                text="pragmaticurl.com/talent",
                url="http://pragmaticurl.com/talent",
                tcourl="https://t.co/MJ0eAtlaS1",
                indices=(102, 125),
            ),
            TextLink(
                text="pragmaticurl.com/contact",
                url="http://pragmaticurl.com/contact",
                tcourl="https://t.co/POWftUprCb",
                indices=(136, 159),
            ),
        ],
        verified=False,
        created=datetime.datetime(2009, 4, 10, 10, 1, 11, tzinfo=datetime.timezone.utc),
        followersCount=209133,
        friendsCount=1395,
        statusesCount=25953,
        favouritesCount=33240,
        listedCount=2344,
        mediaCount=2617,
        location="Amsterdam, The Netherlands",
        protected=False,
        link=TextLink(
            text="pragmaticengineer.com",
            url="https://pragmaticengineer.com/",
            tcourl="https://t.co/x8RulFU4ID",
            indices=(0, 23),
        ),
        profileImageUrl="https://pbs.twimg.com/profile_images/673095429748350976/ei5eeouV_normal.png",
        profileBannerUrl="https://pbs.twimg.com/profile_banners/30192824/1619604364",
        label=None,
    ),
    mentionedUsers=None,
    coordinates=None,
    place=None,
    hashtags=None,
    cashtags=None,
    card=None,
    viewCount=36028,
    vibe=None,
)
