# Generated by Django 4.1.7 on 2023-03-03 20:01

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwitterUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("twitter_id", models.CharField(max_length=30, unique=True)),
                ("username", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                (
                    "account_created_at",
                    models.DateTimeField(verbose_name="Twitter account creation date"),
                ),
                ("location", models.CharField(blank=True, max_length=50)),
                ("followers_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                ("tweet_count", models.IntegerField(default=0)),
                ("listed_count", models.IntegerField(default=0)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("twitter_id", models.CharField(max_length=30, unique=True)),
                ("content", models.CharField(max_length=300)),
                (
                    "published_at",
                    models.DateTimeField(verbose_name="tweet publish date"),
                ),
                ("in_reply_to", models.CharField(blank=True, max_length=30, null=True)),
                ("reply_count", models.IntegerField(default=0)),
                ("retweet_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("quote_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweet_user",
                        to="tweets.twitteruser",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
