# Generated by Django 4.1.7 on 2023-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("twitter_id", models.CharField(max_length=30)),
                ("content", models.CharField(max_length=300)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("scrape_date", models.DateTimeField(verbose_name="date scrapped")),
                ("in_reply_to", models.CharField(blank=True, max_length=30, null=True)),
                ("username", models.CharField(max_length=50)),
                ("user_id", models.CharField(max_length=30)),
                ("reply_count", models.IntegerField(default=0)),
                ("retweet_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("quote_count", models.IntegerField(default=0)),
            ],
        ),
    ]
