# Generated by Django 4.1.7 on 2023-02-28 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="scrape_date",
        ),
        migrations.AddField(
            model_name="tweet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="instance creation date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet",
            name="published_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="tweet publish date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="instance creation date"
            ),
        ),
    ]
