# Generated by Django 4.1.7 on 2023-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_remove_tweet_pub_date_remove_tweet_scrape_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="twitter_id",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
