# Generated by Django 4.1.7 on 2023-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_alter_tweet_twitter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="in_reply_to",
            field=models.CharField(blank=True, default="", max_length=30),
            preserve_default=False,
        ),
    ]
