# Generated by Django 4.1.7 on 2023-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0006_scrappingrequest_recurse"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrappingrequest",
            name="include_replies",
            field=models.BooleanField(default=True),
        ),
    ]
