# Generated by Django 4.1.7 on 2023-04-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0008_tweet_quoted_tweet_id_tweet_retweeted_tweet_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="raw_tweet_object",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
