# Generated by Django 4.1.7 on 2023-04-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0011_rename_quoted_tweet_id_tweet_quoted_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="quoted_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quoted_tweets_set",
                to="tweets.tweet",
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="retweeted_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retweeted_tweets_set",
                to="tweets.tweet",
            ),
        ),
    ]
