# Generated by Django 4.1.7 on 2023-04-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0013_scrappingrequest_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrappingrequest",
            name="twitter_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
