# Generated by Django 4.1.7 on 2023-04-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0014_scrappingrequest_twitter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrappingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("interrupted", "Interrupted"),
                ],
                db_index=True,
                default="created",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="scrappingrequest",
            name="twitter_id",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="scrappingrequest",
            name="username",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="twitter_id",
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="twitteruser",
            name="username",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
