# Generated by Django 4.1.7 on 2023-03-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="in_reply_to",
            new_name="in_reply_to_id",
        ),
        migrations.AddField(
            model_name="tweet",
            name="conversation_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
