# Generated by Django 4.1.7 on 2023-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0007_scrappingrequest_include_replies"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="quoted_tweet_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="tweet",
            name="retweeted_tweet_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="tweet",
            name="view_count",
            field=models.IntegerField(null=True),
        ),
    ]
