# Generated by Django 4.1.7 on 2023-04-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0009_tweet_raw_tweet_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="conversation_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversation_tweets_set",
                to="tweets.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="in_reply_to_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tweet_replies_set",
                to="tweets.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="view_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
