# Generated by Django 4.1.7 on 2023-04-26 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0010_alter_tweet_conversation_tweet_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="quoted_tweet_id",
            new_name="quoted_id",
        ),
        migrations.RenameField(
            model_name="tweet",
            old_name="retweeted_tweet_id",
            new_name="retweeted_id",
        ),
    ]
