# Generated by Django 4.1.7 on 2023-04-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0012_tweet_quoted_tweet_tweet_retweeted_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrappingrequest",
            name="logs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
