# Generated by Django 4.1.7 on 2023-06-11 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0015_alter_scrappingrequest_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScrappingRequest",
            new_name="ScrapingRequest",
        ),
        migrations.RenameField(
            model_name="tweet",
            old_name="scrapping_request",
            new_name="scraping_request",
        ),
    ]
